apiVersion: v1
kind: Service
metadata:
  name: mywebapp
  labels:
    run: mywebapp
spec:
  type: LoadBalancer
  ports:
    - port: 80           
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    run: mywebapp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mywebapp
spec:
  replicas: 3
  selector:
    matchLabels:
      run: mywebapp
  template:
    metadata:
      labels:
        run: mywebapp
    spec:
      containers:
        - name: mysql
          image: mysql
          env:                    
            - name: MYSQL_ROOT_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: myDB
          ports:
            - containerPort: 3306    
        - name: webapp
          image: us.gcr.io/cloud-lab-1-340101/mywebapp:1.0     
          ports:
            - containerPort: 8080